// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebServicoAPI.Models;

public partial class OficinasMecanicasContext : DbContext
{
    public OficinasMecanicasContext(DbContextOptions<OficinasMecanicasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<OficinaMecanica> OficinaMecanica { get; set; }

    public virtual DbSet<ResetarSenha> ResetarSenha { get; set; }

    public virtual DbSet<ServicosPrestados> ServicosPrestados { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<OficinaMecanica>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<ResetarSenha>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Efetivado).HasDefaultValue(false);
            entity.Property(e => e.Excluido).HasDefaultValue(false);

            entity.HasOne(d => d.Usuario).WithMany(p => p.ResetarSenha)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResetarSenha_Usuarios");
        });

        modelBuilder.Entity<ServicosPrestados>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Servico");
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Usuario");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}