// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebServicoAPI.Models;

public partial class OficinaMecanica
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string? Nome { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string? Endereco { get; set; }

    [Unicode(false)]
    public string? Servicos { get; set; }
}