// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;


namespace OficinasMecanicas.Dominio.Entidades
{
    public partial class Usuarios : EntidadeBase
    {
        [StringLength(512)]
        public string Email { get; set; }

        public string PasswordHash { get; set; }

        [StringLength(256)]
        [Unicode(false)]
        public string Username { get; set; }
        

        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<ResetarSenha> ResetarSenha { get; set; } = new List<ResetarSenha>();
    }
}